# Generated by Django 2.1.7 on 2019-02-27 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190226_1450'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likemodel',
            unique_together={('user', 'post')},
        ),
    ]
