# Generated by Django 2.1.7 on 2019-03-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_postmodel_published_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ('-published_date',)},
        ),
        migrations.AddField(
            model_name='user',
            name='hunter_verified',
            field=models.BooleanField(default=False, verbose_name='hunter_verified'),
        ),
    ]
