# Generated by Django 2.1.7 on 2019-03-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190303_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='bio'),
        ),
        migrations.AddField(
            model_name='user',
            name='family_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='family name'),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='full name'),
        ),
        migrations.AddField(
            model_name='user',
            name='given_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='given name'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='user',
            name='site',
            field=models.URLField(blank=True, null=True, verbose_name='site'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hunter_verified',
            field=models.BooleanField(default=False, verbose_name='hunter verified'),
        ),
    ]
